from app import db

class Items(db.Model):
    id =                 db.Column(db.Integer, primary_key=True)
    title =              db.Column(db.String())
    description =        db.Column(db.String())
    tiny_description =   db.Column(db.String())
    short_description =  db.Column(db.String())
    medium_description = db.Column(db.String())
    long_description =   db.Column(db.String())
    price =              db.Column(db.Float())
    shelf_time =         db.Column(db.Integer)
    campus_id =          db.Column(db.Integer)
    last_update =        db.Column(db.Integer)
    archived =           db.Column(db.Integer)
    taxable =            db.Column(db.Integer)
    category_names =     db.Column(db.String())
    vendor =             db.Column(db.String())
    source =             db.Column(db.String())
    notes =              db.Column(db.String())
    total_cal =          db.Column(db.Integer)
    num_servings =       db.Column(db.Integer)
    ingredients =        db.Column(db.String())
    calories =           db.Column(db.Integer)
    proteins =           db.Column(db.Integer)
    sugar =              db.Column(db.Integer)
    carbohydrates =      db.Column(db.Integer)
    fat =                db.Column(db.Integer)
    consumer_category =  db.Column(db.String())
    ws_case_size =       db.Column(db.Integer)
    kiosk_ship_qty =     db.Column(db.Integer)
    pick_station =       db.Column(db.Integer)
    fc_title =           db.Column(db.String())
    width_space =        db.Column(db.Float())
    height_space =       db.Column(db.Float())
    depth_space =        db.Column(db.Float())
    slotted_width =      db.Column(db.Float())
    tag_volume =         db.Column(db.Integer)
    delivery_option =    db.Column(db.String())
    tag_applied_by =     db.Column(db.String())

